# Generated by Django 4.0.5 on 2022-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_pay_id', models.PositiveIntegerField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=False)),
                ('summ', models.PositiveSmallIntegerField(default=800)),
                ('from_date', models.DateField()),
                ('untill_date', models.DateField()),
                ('remains_lessons', models.PositiveSmallIntegerField(blank=True, editable=False)),
                ('buied_lessons', models.PositiveSmallIntegerField(default=12)),
                ('currency', models.CharField(choices=[('MDL', 'MDL'), ('EUR', 'EUR'), ('USD', 'USD')], default='MDL', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_v_id', models.PositiveIntegerField(blank=True, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
