# Generated by Django 4.0.5 on 2022-09-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('lessons', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='users.client'),
        ),
        migrations.AddField(
            model_name='visit',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lessons',
            field=models.ManyToManyField(blank=True, editable=False, related_name='+', to='lessons.lesson'),
        ),
    ]
