# Generated by Django 4.0.5 on 2022-06-20 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('about', models.TextField()),
                ('meadia_repr', models.FileField(upload_to='lessons/')),
                ('quantity', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MaxValueValidator(35)])),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.TimeField()),
                ('loaction', models.URLField(default='https://goo.gl/maps/HZwWj15NgYrt2vBz9')),
                ('studio_numb', models.IntegerField(choices=[(101, 'Studio №=101'), (109, 'Studio №=109'), (115, 'Studio №=115'), (201, 'Studio №=201'), (205, 'Studio №=205'), (208, 'Studio №=208')])),
            ],
        ),
    ]
