# Generated by Django 4.0.5 on 2022-06-21 15:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='The Space project[Center]', max_length=35)),
                ('geo', models.URLField(default='https://goo.gl/maps/HZwWj15NgYrt2vBz9')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('about', models.TextField(default='')),
                ('avatar', models.ImageField(blank=True, upload_to='students/')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the local format: '0XXXXXXXX'.", regex='^0?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('geo_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.location')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('about', models.TextField()),
                ('meadia_repr', models.ImageField(upload_to='lessons/')),
                ('quantity', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MaxValueValidator(35)])),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.TimeField()),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studio')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
