# Generated by Django 4.0.5 on 2022-09-07 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(default='Contemporary Dance', max_length=35)),
                ('about', models.TextField(blank=True, null=True)),
                ('more', models.URLField(blank=True, null=True)),
                ('meadia_repr', models.ImageField(blank=True, null=True, upload_to='activities/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='The Space project[Center]', max_length=35)),
                ('url_name', models.CharField(blank=True, editable=False, max_length=35)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('about', models.TextField(blank=True, null=True)),
                ('geo', models.URLField(default='https://goo.gl/maps/HZwWj15NgYrt2vBz9')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='locations/studios/')),
                ('about', models.TextField(blank=True, null=True)),
                ('geo_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studios', to='lessons.location')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(35)])),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_at', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.activitytype')),
            ],
            options={
                'ordering': ['start_date', 'start_time', 'end_at'],
            },
        ),
    ]
