# Generated by Django 4.0.5 on 2022-09-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='users.client'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='queue',
            field=models.ManyToManyField(blank=True, related_name='+', to='users.client'),
        ),
    ]
